# Generated by Django 3.0.5 on 2020-05-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200523_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
