# Generated by Django 3.0.5 on 2020-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200523_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, default='9133398434', editable=False, max_length=10, unique=True),
        ),
    ]
