# Generated by Django 3.0.6 on 2020-05-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_doctor_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='salary',
            field=models.IntegerField(default=40000),
        ),
    ]
