# Generated by Django 3.0.5 on 2020-05-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_cases', '0001_initial'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_bill', to='all_cases.case'),
        ),
    ]
